// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("https://dev-finance.netlify.app/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("+ Nova Transação")).click()
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Extra")
    await driver.findElement(By.id("amount")).click()
    await driver.findElement(By.id("amount")).sendKeys("956.85")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2024-06-30")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.linkText("+ Nova Transação")).click()
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Aniversario")
    await driver.findElement(By.id("amount")).click()
    await driver.findElement(By.id("amount")).sendKeys("200.00")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2024-06-24")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.linkText("+ Nova Transação")).click()
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Pelucia")
    await driver.findElement(By.id("amount")).click()
    await driver.findElement(By.id("amount")).sendKeys("150.00")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2024-07-22")
    await driver.findElement(By.css("button")).click()
    {
      const element = await driver.findElement(By.css("button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("tr:nth-child(9) img")).click()
    await driver.findElement(By.linkText("+ Nova Transação")).click()
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Pelucia")
    await driver.findElement(By.id("amount")).click()
    await driver.findElement(By.id("amount")).sendKeys("-150.00")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2024-07-22")
    await driver.findElement(By.css("button")).click()
    {
      const element = await driver.findElement(By.css("button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("balance")).click()
    await driver.findElement(By.linkText("+ Nova Transação")).click()
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Social")
    await driver.findElement(By.id("amount")).click()
    await driver.findElement(By.id("amount")).sendKeys("5.00")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.id("date")).sendKeys("2024-07-19")
    await driver.findElement(By.css("button")).click()
  })
})
